export const permissionKeys = [
  "company.read",
  "company.update",
  "users.read",
  "users.manage",
  "roles.read",
  "roles.manage",
  "product.read",
  "product.create",
  "product.update",
  "product.delete",
  "product.publish",
  "product.export",
  "category.read",
  "category.manage",
  "attribute.read",
  "attribute.manage",
  "inventory.read",
  "inventory.adjust",
  "inventory.transfer",
  "inventory.reserve",
  "imports.read",
  "imports.run",
  "exports.read",
  "exports.run",
  "integration.read",
  "integration.configure",
  "integration.sync",
  "gs1.read",
  "gs1.manage",
  "audit.read",
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const rolePermissionMap = {
  owner: permissionKeys,
  admin: permissionKeys,
  product_manager: [
    "company.read",
    "users.read",
    "product.read",
    "product.create",
    "product.update",
    "product.publish",
    "product.export",
    "category.read",
    "category.manage",
    "attribute.read",
    "attribute.manage",
    "inventory.read",
    "imports.read",
    "imports.run",
    "exports.read",
    "exports.run",
    "integration.read",
    "gs1.read",
    "gs1.manage",
  ],
  inventory_manager: [
    "company.read",
    "product.read",
    "inventory.read",
    "inventory.adjust",
    "inventory.transfer",
    "inventory.reserve",
    "imports.read",
    "imports.run",
    "exports.read",
    "exports.run",
    "integration.read",
  ],
  employee: [
    "company.read",
    "product.read",
    "product.create",
    "product.update",
    "category.read",
    "attribute.read",
    "inventory.read",
    "imports.read",
    "exports.read",
    "integration.read",
    "gs1.read",
  ],
  viewer: [
    "company.read",
    "product.read",
    "category.read",
    "attribute.read",
    "inventory.read",
    "imports.read",
    "exports.read",
    "integration.read",
    "gs1.read",
  ],
} as const satisfies Record<string, readonly PermissionKey[]>;
