import { ClockCounterClockwise, Plus, Trash, UserPlus, Warehouse as WarehouseIcon } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { PageHeader } from "../components/page-header";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../components/ui/table";
import { api, errorMessage } from "../lib/api";

function MutationNotice({ error, success }: { error?: unknown; success?: string }) { return <>{error && <p className="form-alert" role="alert">{errorMessage(error)}</p>}{success && <p className="success-alert">{success}</p>}</>; }

type Category = { id: string; name: string; slug: string; description?: string; parentId?: string; _count: { products: number; children: number } };
type Brand = { id: string; name: string; slug: string; manufacturer?: string; _count: { products: number } };
export function CategoriesPage() {
  const client = useQueryClient(); const [message, setMessage] = useState("");
  const query = useQuery({ queryKey: ["categories"], queryFn: () => api<Category[]>("/categories") });
  const brands = useQuery({ queryKey: ["brands"], queryFn: () => api<Brand[]>("/brands") });
  const create = useMutation({ mutationFn: (input: unknown) => api("/categories", { method: "POST", body: JSON.stringify(input) }), onSuccess: async () => { setMessage("Category created."); await client.invalidateQueries({ queryKey: ["categories"] }); } });
  const createBrand = useMutation({ mutationFn: (input: unknown) => api("/brands", { method: "POST", body: JSON.stringify(input) }), onSuccess: () => client.invalidateQueries({ queryKey: ["brands"] }) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const data = new FormData(event.currentTarget); const name = String(data.get("name")); create.mutate({ name, slug: String(data.get("slug")), description: String(data.get("description")) || undefined, parentId: String(data.get("parentId")) || undefined }); }
  function submitBrand(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); createBrand.mutate({ name: String(data.get("brandName")), slug: String(data.get("brandSlug")), manufacturer: String(data.get("manufacturer")) || undefined }); }
  return <div className="page-stack"><PageHeader eyebrow="Catalog" title="Categories" description="Internal taxonomy stays independent from website and eMAG category mappings." />
    <Card className="panel"><div className="panel-header"><div><h2>Brands</h2><p>Reusable product brands and manufacturer identity.</p></div><Badge tone="neutral">{brands.data?.length ?? 0}</Badge></div><form className="inline-form" onSubmit={submitBrand}><div className="field"><label>Name</label><Input name="brandName" required /></div><div className="field"><label>Slug</label><Input name="brandSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></div><div className="field"><label>Manufacturer</label><Input name="manufacturer" /></div><Button type="submit" disabled={createBrand.isPending}>Add brand</Button></form>{createBrand.error && <p className="form-alert">{errorMessage(createBrand.error)}</p>}<div className="tag-row brand-tags">{brands.data?.map((brand) => <span key={brand.id}>{brand.name} · {brand._count.products} products</span>)}</div></Card>
    <div className="two-column"><Card className="panel"><div className="panel-header"><div><h2>Create category</h2><p>Add a root or nested internal category.</p></div><Plus size={18} /></div><form className="form-stack compact-form" onSubmit={submit}><div className="field"><label>Name</label><Input name="name" required minLength={2} /></div><div className="field"><label>Slug</label><Input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></div><div className="field"><label>Parent</label><select className="select-control" name="parentId"><option value="">Root category</option>{query.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Description</label><Input name="description" /></div><MutationNotice error={create.error} success={message} /><Button type="submit" disabled={create.isPending}>Create category</Button></form></Card>
      <Card className="data-card"><div className="panel-header inventory-header"><div><h2>Taxonomy</h2><p>{query.data?.length ?? 0} internal categories</p></div></div><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Slug</TableHead><TableHead>Products</TableHead><TableHead>Children</TableHead></TableRow></TableHeader><TableBody>{query.data?.map((item) => <TableRow key={item.id}><TableCell className="font-semibold">{item.name}</TableCell><TableCell className="text-muted">{item.slug}</TableCell><TableCell>{item._count.products}</TableCell><TableCell>{item._count.children}</TableCell></TableRow>)}</TableBody></Table></Card></div>
  </div>;
}

type WarehouseRecord = { id: string; code: string; name: string; isActive: boolean; locations: Array<{ id: string; code: string; name: string; type: string }>; _count: { stockLevels: number } };
export function WarehousesPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["warehouses"], queryFn: () => api<WarehouseRecord[]>("/warehouses") });
  const create = useMutation({ mutationFn: (input: unknown) => api("/warehouses", { method: "POST", body: JSON.stringify(input) }), onSuccess: () => client.invalidateQueries({ queryKey: ["warehouses"] }) });
  const createLocation = useMutation({ mutationFn: ({ warehouseId, input }: { warehouseId: string; input: unknown }) => api(`/warehouses/${warehouseId}/locations`, { method: "POST", body: JSON.stringify(input) }), onSuccess: () => client.invalidateQueries({ queryKey: ["warehouses"] }) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ code: String(data.get("code")), name: String(data.get("name")) }); }
  function submitLocation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); createLocation.mutate({ warehouseId: String(data.get("warehouseId")), input: { code: String(data.get("code")), name: String(data.get("name")), type: String(data.get("type")) } }); }
  return <div className="page-stack"><PageHeader eyebrow="Operations" title="Warehouses" description="Configure stock sources and logical locations before receiving inventory." />
    <div className="two-column"><div className="channel-side-stack"><Card className="panel"><div className="panel-header"><div><h2>New warehouse</h2><p>Codes are unique inside this workspace.</p></div><WarehouseIcon size={18} /></div><form className="form-stack compact-form" onSubmit={submit}><div className="field"><label>Code</label><Input name="code" required pattern="[A-Za-z0-9._-]+" /></div><div className="field"><label>Name</label><Input name="name" required minLength={2} /></div><MutationNotice error={create.error} /><Button type="submit" disabled={create.isPending}>Create warehouse</Button></form></Card><Card className="panel"><div className="panel-header"><div><h2>New location</h2><p>Optional logical bins for receiving, sellable, damaged, or quarantine stock.</p></div><Plus size={18} /></div><form className="form-stack compact-form" onSubmit={submitLocation}><div className="field"><label>Warehouse</label><select className="select-control" name="warehouseId" required><option value="">Choose warehouse</option>{query.data?.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="form-grid"><div className="field"><label>Code</label><Input name="code" required /></div><div className="field"><label>Name</label><Input name="name" required /></div></div><div className="field"><label>Type</label><select className="select-control" name="type"><option>SELLABLE</option><option>RECEIVING</option><option>DAMAGED</option><option>QUARANTINE</option><option>RETURNS</option></select></div><MutationNotice error={createLocation.error} /><Button type="submit" disabled={createLocation.isPending}>Create location</Button></form></Card></div>
      <Card className="data-card"><Table><TableHeader><TableRow><TableHead>Warehouse</TableHead><TableHead>Locations</TableHead><TableHead>Balances</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{query.data?.map((item) => <TableRow key={item.id}><TableCell><strong>{item.name}</strong><small className="block text-muted">{item.code}</small></TableCell><TableCell><div className="tag-row">{item.locations.map((location) => <span key={location.id}>{location.code} · {location.type}</span>)}{!item.locations.length && <small className="text-muted">None</small>}</div></TableCell><TableCell>{item._count.stockLevels}</TableCell><TableCell><Badge tone={item.isActive ? "success" : "neutral"}>{item.isActive ? "Active" : "Inactive"}</Badge></TableCell></TableRow>)}</TableBody></Table></Card></div>
  </div>;
}

type Role = { id: string; key: string; name: string };
type Member = { id: string; user: { id: string; email: string; displayName: string; status: string; lastLoginAt?: string }; role: Role };
type Invitation = { id: string; email: string; expiresAt: string; acceptedAt?: string; revokedAt?: string; role: Role; invitedBy: { displayName: string } };
export function UsersPage() {
  const client = useQueryClient(); const [issued, setIssued] = useState<string>();
  const users = useQuery({ queryKey: ["users"], queryFn: () => api<Member[]>("/users") }); const roles = useQuery({ queryKey: ["roles"], queryFn: () => api<Role[]>("/roles") });
  const invitations = useQuery({ queryKey: ["invitations"], queryFn: () => api<Invitation[]>("/invitations") });
  const invite = useMutation({ mutationFn: (input: unknown) => api<{ token: string }>("/invitations", { method: "POST", body: JSON.stringify(input) }), onSuccess: async (result) => { setIssued(`${window.location.origin}/accept-invitation#${encodeURIComponent(result.token)}`); await Promise.all([client.invalidateQueries({ queryKey: ["users"] }), client.invalidateQueries({ queryKey: ["invitations"] })]); } });
  const updateMember = useMutation({ mutationFn: ({ id, input }: { id: string; input: unknown }) => api(`/memberships/${id}`, { method: "PATCH", body: JSON.stringify(input) }), onSuccess: () => client.invalidateQueries({ queryKey: ["users"] }) });
  const revoke = useMutation({ mutationFn: (invitationId: string) => api(`/invitations/${invitationId}`, { method: "DELETE" }), onSuccess: () => client.invalidateQueries({ queryKey: ["invitations"] }) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIssued(undefined); const data = new FormData(event.currentTarget); invite.mutate({ email: String(data.get("email")), displayName: String(data.get("displayName")), roleId: String(data.get("roleId")), expiresInDays: 7 }); }
  return <div className="page-stack"><PageHeader eyebrow="Governance" title="Users" description="Only administrators can issue invitations and assign least-privilege roles." />
    <div className="two-column"><Card className="panel"><div className="panel-header"><div><h2>Invite user</h2><p>The activation link is shown once.</p></div><UserPlus size={18} /></div><form className="form-stack compact-form" onSubmit={submit}><div className="field"><label>Name</label><Input name="displayName" required /></div><div className="field"><label>Email</label><Input name="email" type="email" required /></div><div className="field"><label>Role</label><select name="roleId" className="select-control" required><option value="">Choose role</option>{roles.data?.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></div><MutationNotice error={invite.error} /><Button type="submit" disabled={invite.isPending}>Issue invitation</Button>{issued && <div className="secret-once"><strong>Copy this invitation link now</strong><code>{issued}</code><Button type="button" size="sm" variant="secondary" onClick={() => void navigator.clipboard.writeText(issued)}>Copy link</Button></div>}</form></Card>
      <Card className="data-card"><Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead>Last login</TableHead></TableRow></TableHeader><TableBody>{users.data?.map((item) => <TableRow key={item.id}><TableCell><strong>{item.user.displayName}</strong><small className="block text-muted">{item.user.email}</small></TableCell><TableCell><select aria-label={`Role for ${item.user.displayName}`} className="select-control table-select" value={item.role.id} onChange={(event) => updateMember.mutate({ id: item.id, input: { roleId: event.target.value } })}>{roles.data?.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></TableCell><TableCell><button className="status-button" type="button" onClick={() => updateMember.mutate({ id: item.id, input: { status: item.user.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE" } })}><Badge tone={item.user.status === "ACTIVE" ? "success" : "warning"}>{item.user.status}</Badge></button></TableCell><TableCell>{item.user.lastLoginAt ? new Date(item.user.lastLoginAt).toLocaleString("ro-RO") : "Never"}</TableCell></TableRow>)}</TableBody></Table>{updateMember.error && <p className="form-alert table-alert">{errorMessage(updateMember.error)}</p>}</Card></div>
    <Card className="data-card"><div className="panel-header inventory-header"><div><h2>Invitations</h2><p>Pending, accepted, expired, and revoked access grants.</p></div></div><Table><TableHeader><TableRow><TableHead>Email</TableHead><TableHead>Role</TableHead><TableHead>Invited by</TableHead><TableHead>Expires</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{invitations.data?.map((invitation) => { const status = invitation.acceptedAt ? "Accepted" : invitation.revokedAt ? "Revoked" : new Date(invitation.expiresAt) < new Date() ? "Expired" : "Pending"; return <TableRow key={invitation.id}><TableCell>{invitation.email}</TableCell><TableCell>{invitation.role.name}</TableCell><TableCell>{invitation.invitedBy.displayName}</TableCell><TableCell>{new Date(invitation.expiresAt).toLocaleString("ro-RO")}</TableCell><TableCell><Badge tone={status === "Accepted" ? "success" : status === "Pending" ? "info" : "neutral"}>{status}</Badge></TableCell><TableCell>{status === "Pending" && <Button size="icon" variant="ghost" aria-label="Revoke invitation" onClick={() => revoke.mutate(invitation.id)}><Trash size={14} /></Button>}</TableCell></TableRow>; })}</TableBody></Table></Card>
  </div>;
}

type AuditEntry = { id: string; action: string; entityType: string; entityId?: string; createdAt: string; actor?: { displayName: string; email: string }; before?: unknown; after?: unknown };
export function AuditPage() {
  const query = useQuery({ queryKey: ["audit"], queryFn: () => api<{ data: AuditEntry[] }>("/audit-logs?limit=100") });
  return <div className="page-stack"><PageHeader eyebrow="Governance" title="Audit log" description="Immutable operator history across products, stock, access, files, and integrations." actions={<ClockCounterClockwise size={20} />} /><Card className="data-card"><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Action</TableHead><TableHead>Entity</TableHead><TableHead>Actor</TableHead><TableHead>Change</TableHead></TableRow></TableHeader><TableBody>{query.data?.data.map((item) => <TableRow key={item.id}><TableCell className="whitespace-nowrap">{new Date(item.createdAt).toLocaleString("ro-RO")}</TableCell><TableCell><Badge tone="neutral">{item.action}</Badge></TableCell><TableCell>{item.entityType}<small className="block text-muted">{item.entityId}</small></TableCell><TableCell>{item.actor?.displayName ?? "System"}</TableCell><TableCell><details><summary>View</summary><pre className="json-preview">{JSON.stringify({ before: item.before, after: item.after }, null, 2)}</pre></details></TableCell></TableRow>)}</TableBody></Table></Card></div>;
}
