import { CheckCircle, Warning, XCircle } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { PageHeader } from "../components/page-header";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { api, errorMessage } from "../lib/api";
import { formatExactTime, formatRelativeTime } from "../lib/utils";

type Notification = {
  id: string;
  severity: "INFO" | "WARNING" | "ERROR";
  title: string;
  message: string;
  entityType?: string;
  entityId?: string;
  createdAt: string;
  resolvedAt?: string;
};

type NotificationPage = { data: Notification[] };

export function NotificationsPage() {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["notifications"], queryFn: () => api<NotificationPage>("/notifications?limit=100"), refetchInterval: 30_000 });
  const resolve = useMutation({ mutationFn: (id: string) => api(`/notifications/${id}/resolve`, { method: "PATCH" }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["notifications"] }), client.invalidateQueries({ queryKey: ["workspace-summary"] })]); } });

  const open = query.data?.data.filter((item) => !item.resolvedAt) ?? [];
  const resolved = query.data?.data.filter((item) => item.resolvedAt).slice(0, 15) ?? [];
  return <div className="page-stack">
    <PageHeader title="Notifications" description="Operational issues generated by catalog, inventory, imports and connected channels." />
    {query.isError && <p className="form-alert">{errorMessage(query.error)}</p>}
    {resolve.error && <p className="form-alert">{errorMessage(resolve.error)}</p>}
    <section className="notification-list" aria-label="Operational notifications">
      {open.map((item) => {
        const Icon = item.severity === "ERROR" ? XCircle : item.severity === "WARNING" ? Warning : CheckCircle;
        const destination = item.entityType === "Product" && item.entityId ? `/products/${item.entityId}` : "/synchronization";
        return <article key={item.id} className={`notification-row severity-${item.severity.toLowerCase()}`}>
          <Icon size={19} weight="duotone" aria-hidden="true" />
          <div><div><strong>{item.title}</strong><Badge tone={item.severity === "ERROR" ? "danger" : item.severity === "WARNING" ? "warning" : "info"}>{item.severity.toLowerCase()}</Badge></div><p>{item.message}</p><small title={formatExactTime(item.createdAt)}>{formatRelativeTime(item.createdAt)}</small></div>
          <div><Button asChild size="sm" variant="ghost"><Link to={destination}>Open</Link></Button><Button size="sm" variant="secondary" onClick={() => resolve.mutate(item.id)} disabled={resolve.isPending}>Resolve</Button></div>
        </article>;
      })}
      {!query.isLoading && !open.length && <div className="inline-success notification-empty"><CheckCircle size={22} aria-hidden="true" /><span><strong>All clear</strong><small>There are no unresolved operational notifications.</small></span></div>}
    </section>
    {resolved.length > 0 && <details className="notification-history">
      <summary>Recently resolved ({resolved.length})</summary>
      <section className="notification-list" aria-label="Resolved notifications">
        {resolved.map((item) => <article key={item.id} className="notification-row resolved">
          <CheckCircle size={19} weight="duotone" aria-hidden="true" />
          <div><div><strong>{item.title}</strong><Badge tone="neutral">resolved</Badge></div><p>{item.message}</p><small title={formatExactTime(item.resolvedAt!)}>Resolved {formatRelativeTime(item.resolvedAt!)}</small></div>
        </article>)}
      </section>
    </details>}
  </div>;
}
